package org.training.account.service.model.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.training.account.service.model.AccountStatus;
import org.training.account.service.model.AccountType;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Entity class representing a bank account.
 * 
 * <p>This entity stores all account-related information including the account number,
 * type, status, balance, and associated user. It is persisted to the database and
 * serves as the core data model for the Account Service.</p>
 * 
 * @author Training Team
 * @version 1.0
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Account {

    /**
     * Unique identifier for the account, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long accountId;

    /**
     * The unique account number (e.g., "0600140000001").
     * Generated using the Sequence Generator service with a bank prefix.
     */
    private String accountNumber;

    /**
     * The type of account (SAVINGS_ACCOUNT, FIXED_DEPOSIT, LOAN_ACCOUNT).
     */
    @Enumerated(EnumType.STRING)
    private AccountType accountType;

    /**
     * The current status of the account (PENDING, ACTIVE, BLOCKED, CLOSED).
     */
    @Enumerated(EnumType.STRING)
    private AccountStatus accountStatus;

    /**
     * The date when the account was opened.
     * Automatically set to the current date when the account is created.
     */
    @CreationTimestamp
    private LocalDate openingDate;

    /**
     * The current available balance in the account.
     */
    private BigDecimal availableBalance;

    /**
     * The ID of the user who owns this account.
     * References the User entity in the User Service.
     */
    private Long userId;
}
